### ISSUE TITLE
user_storie_7

### ISSUE THREAD

**Issue by YaroslavBoiko** [SA-TeamBerlin/airport#32]
### Description
The main idea behind the implementation is that the system engineer was able to use data from existing Assets for new Assets (that is, it would be necessary to implement a data call from other objects of the same class). This is to avoid repeatedly entering the same data for multiple Assets.

### Expected outcome
Users can select pre-populated fields/information from an Asset to be replicated/copied to other Assets.

**Comment by myroslavarm** [comment]
skipping this for now
