### ISSUE TITLE
user_storie_8

### ISSUE THREAD

**Issue by YaroslavBoiko** [SA-TeamBerlin/airport#33]
### Description
The main idea behind the implementation is that users (accountant, systems engineer, maintenance planner, maintenance planner) can change the assets to Capex that were raised to buy/pay for them - or the project that designed them / created them. 

This is to ensure that assets can be tracked, depreciated and disposed of properly.

Functionalities can be made as a separate class or implemented directly in the Asset class. Therefore, in the previous way(realization of users' story), it is best to implement a separate class in the services directory.

### Expected outcome
Capex or Project number is recorded against the specific Asset(s) that were acquired/developed;

And Asset(s) can be selected/tracked by the Capex or Project that they are associated to;

And (planned/unplanned) maintenance costs over the lifetime of the Asset(s) can be determined through the Work Orders associated to them.

**Comment by myroslavarm** [comment]
there are some things that need to be improved:

- [x] AssetFinancialDetail entity has to be added in 1-2-1 correspondence to Asset (key type also Asset)

- [x] Project entity needs to be added to signify a capital expenditure project

**Comment by myroslavarm** [comment]
this is implemented now
