### ISSUE TITLE
User story 9

### ISSUE THREAD

**Issue by sashkopotapov** [SA-TeamBerlin/airport#36]
**Description**
Implement an opportunity to record the Role, Business Unit or Organisation that owns an Asset (or Asset Type)

**Expected outcome**
The system engineer knows who manages the budget for the Asset (or Asset Type). 

**Describe alternatives you've considered**

**Acceptance criteria**
Asset / Asset Type is associated with the applicable Asset Owner and
the date/time of the association is recorded.

**Comment by myroslavarm** [comment]
- [x] `Role`, `BusinessUnit` and `Organisation` all have to be separate entities that are associated both to `Asset` and `AssetType`.

- [x] Date/time association means that an asset can have a different owner at different times : figure out how to specify this on the model level.
