### ISSUE TITLE
User story 5 

### ISSUE THREAD

**Issue by Komashka** [SA-TeamBerlin/airport#38]
**Description**
System Engineer, Maintenance Planner, Maintenance Scheduler must have the right to register and classify an Asset

**Expected outcome**
System Engineer, Maintenance Planner, Maintenance Scheduler can track and depreciate Asset. Also, its maintenance can be planned, scheduled, and performed on it if required.

**Acceptance criteria**
Asset description/record is created and associated with the relevant Asset Type.
A new, unique Asset Id has been generated and assigned to the Asset.
Relevant information (mandatory Asset attributes based on Asset Type) has been captured/populated.

#2 -  here we develop functionality for System Engineer to add and define Asset Class.

**Comment by myroslavarm** [comment]
issue https://github.com/SA-TeamBerlin/airport/issues/19 and the relating PRs are part of this AC05 implementation. in general, the AC05 story requirements were already implemented so this can be closed.
