### ISSUE TITLE
User story 6

### ISSUE THREAD

**Issue by Komashka** [SA-TeamBerlin/airport#39]
The Bulk Upload feature helps you upload or update multiple documents at the same time without needing to go to Add new document and select each document individually. 

**Description**
System Engineer must be able to bulk upload and register Assets from a completed project. So that, all Assets developed/delivered by the project can be tracked and depreciated, and maintenance can be planned, scheduled and performed on them.

**Acceptance criteria**
In a bulk upload:
Asset description/record is created and associated with the relevant Asset Type;
A new, unique Asset Id has been generated and assigned to the Asset;
Relevant information (mandatory Asset attributes based on Asset Type) has been captured/populated.

This can be done with the usage of functionality which we provide for AC05 case ( register and classify an Asset).

**Comment by myroslavarm** [comment]
skipping this for now
